version: '3.8'

services:

  thedatabase:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: postgres
    ports: 
      - '5432:5432'

  web:
    build: .
    ports:
      - "3020:3000"
    volumes:
      - .:/web
    depends_on:
      - thedatabase
    command: rails s -b 0.0.0.0

  redis:
    image: redis:7.0
    environment:
      REDIS_PASSWORD: 'yourpassword'
    command: redis-server --requirepass yourpassword
    # volumes:
    #   - ./redis:/var/lib/redis/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  mailcatcher:
    image: "schickling/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"

